Need to debug configure.in

diff --git a/ctai/build-sys-template/configure.in b/ctai/build-sys-template/configure.in
--- a/ctai/build-sys-template/configure.in
+++ b/ctai/build-sys-template/configure.in
@@ -106,14 +106,14 @@ then
       echo "*         $file"
     done
     cat 1>&2 <<-EOF
-	*   This indicates that you previously built in the source tree.
-	*   A source tree build can confuse the separate objdir build.
-	*
-	*   To clean up the source tree:
-	*     1. cd $_topsrcdir
-	*     2. gmake distclean
-	***
-	EOF
+  *   This indicates that you previously built in the source tree.
+  *   A source tree build can confuse the separate objdir build.
+  *
+  *   To clean up the source tree:
+  *     1. cd $_topsrcdir
+  *     2. gmake distclean
+  ***
+  EOF
     exit 1
     break
   fi
@@ -125,18 +125,18 @@ dnl ==============================================================
 dnl TODO Make this better, ideally this would clobber automaticially
 if test -e $_objdir/CLOBBER; then
   if test $_topsrcdir/CLOBBER -nt $_objdir/CLOBBER; then
-    echo "	***"
-    echo "	*	The CLOBBER file has been updated, indicating that an incremental build"
-    echo "	*	since your last build will probably not work. A full build is required."
-    echo "	*	The change that caused this is:"
-    cat $_topsrcdir/CLOBBER | sed '/^#/d' | sed 's/^/	*	/'
-    echo "	*	"
-    echo "	*	The easiest way to fix this is to manually delete your objdir:"
-    echo "	*	rm -rf $_objdir"
-    echo "	*	"
-    echo "	*	Or, if you know this clobber doesn't apply to you, it can be ignored with:"
-    echo "	*	cp '$_topsrcdir/CLOBBER' $_objdir"
-    echo "	***"
+    echo "  ***"
+    echo "  * The CLOBBER file has been updated, indicating that an incremental build"
+    echo "  * since your last build will probably not work. A full build is required."
+    echo "  * The change that caused this is:"
+    cat $_topsrcdir/CLOBBER | sed '/^#/d' | sed 's/^/ * /'
+    echo "  * "
+    echo "  * The easiest way to fix this is to manually delete your objdir:"
+    echo "  * rm -rf $_objdir"
+    echo "  * "
+    echo "  * Or, if you know this clobber doesn't apply to you, it can be ignored with:"
+    echo "  * cp '$_topsrcdir/CLOBBER' $_objdir"
+    echo "  ***"
     exit 1
     break;
   fi
@@ -322,16 +322,16 @@ if test -n "$CROSS_COMPILE" -a "$target" != "$host"; then
 
     AC_MSG_CHECKING([whether the host c compiler ($HOST_CC $HOST_CFLAGS $HOST_LDFLAGS) works])
     AC_TRY_COMPILE([], [return(0);],
-	[ac_cv_prog_hostcc_works=1 AC_MSG_RESULT([yes])],
-	AC_MSG_ERROR([installation or configuration problem: host compiler $HOST_CC cannot create executables.]) )
+  [ac_cv_prog_hostcc_works=1 AC_MSG_RESULT([yes])],
+  AC_MSG_ERROR([installation or configuration problem: host compiler $HOST_CC cannot create executables.]) )
 
     CC="$HOST_CXX"
     CFLAGS="$HOST_CXXFLAGS"
 
     AC_MSG_CHECKING([whether the host c++ compiler ($HOST_CXX $HOST_CXXFLAGS $HOST_LDFLAGS) works])
     AC_TRY_COMPILE([], [return(0);],
-	[ac_cv_prog_hostcxx_works=1 AC_MSG_RESULT([yes])],
-	AC_MSG_ERROR([installation or configuration problem: host compiler $HOST_CXX cannot create executables.]) )
+  [ac_cv_prog_hostcxx_works=1 AC_MSG_RESULT([yes])],
+  AC_MSG_ERROR([installation or configuration problem: host compiler $HOST_CXX cannot create executables.]) )
 
     CC=$_SAVE_CC
     CFLAGS=$_SAVE_CFLAGS
@@ -1541,9 +1541,9 @@ if test "$GNU_CC"; then
    [_SAVE_LDFLAGS=$LDFLAGS; _SAVE_LIBS=$LIBS
     ac_cv_mkshlib_force_and_unforce="no"
     exec 3<&0 <<LOOP_INPUT
-	force="-Wl,--whole-archive";   unforce="-Wl,--no-whole-archive"
-	force="-Wl,-z -Wl,allextract"; unforce="-Wl,-z -Wl,defaultextract"
-	force="-Wl,-all";              unforce="-Wl,-none"
+  force="-Wl,--whole-archive";   unforce="-Wl,--no-whole-archive"
+  force="-Wl,-z -Wl,allextract"; unforce="-Wl,-z -Wl,defaultextract"
+  force="-Wl,-all";              unforce="-Wl,-none"
 LOOP_INPUT
     while read line
     do
@@ -2006,11 +2006,11 @@ ia64*-hpux*)
 *-hpux*)
     DLL_SUFFIX=".sl"
     if test ! "$GNU_CC"; then
-    	DSO_LDOPTS='-b -Wl,+s'
-    	DSO_CFLAGS=""
-    	DSO_PIC_CFLAGS="+Z"
-    	MKSHLIB='$(CXX) $(CXXFLAGS) $(DSO_LDOPTS) -L$(LIBXUL_DIST)/bin -o $@'
-    	MKCSHLIB='$(LD) -b +s -L$(LIBXUL_DIST)/bin -o $@'
+      DSO_LDOPTS='-b -Wl,+s'
+      DSO_CFLAGS=""
+      DSO_PIC_CFLAGS="+Z"
+      MKSHLIB='$(CXX) $(CXXFLAGS) $(DSO_LDOPTS) -L$(LIBXUL_DIST)/bin -o $@'
+      MKCSHLIB='$(LD) -b +s -L$(LIBXUL_DIST)/bin -o $@'
         CXXFLAGS="$CXXFLAGS -Wc,-ansi_for_scope,on"
     else
         DSO_LDOPTS='-b -E +s'
@@ -2064,11 +2064,11 @@ ia64*-hpux*)
 
     case "${target_cpu}" in
     alpha*)
-    	CFLAGS="$CFLAGS -mieee"
-    	CXXFLAGS="$CXXFLAGS -mieee"
+      CFLAGS="$CFLAGS -mieee"
+      CXXFLAGS="$CXXFLAGS -mieee"
     ;;
     i*86)
-    	USE_ELF_DYNSTR_GC=1
+      USE_ELF_DYNSTR_GC=1
     ;;
     mips*)
         MOZ_DEBUG_FLAGS="-g" # We want inlining
@@ -2262,8 +2262,8 @@ ia64*-hpux*)
             LDFLAGS="$LDFLAGS -SAFESEH"
         fi
 
-    	AC_DEFINE(_X86_)
-	;;
+      AC_DEFINE(_X86_)
+  ;;
     x86_64-*)
         if test -n "$_WIN32_MSVC"; then
             DSO_LDOPTS="$DSO_LDOPTS -MACHINE:X64"
@@ -2271,12 +2271,12 @@ ia64*-hpux*)
         AC_DEFINE(_AMD64_)
         ;;
     *)
-    	AC_DEFINE(_CPU_ARCH_NOT_DEFINED)
-	;;
+      AC_DEFINE(_CPU_ARCH_NOT_DEFINED)
+  ;;
     esac
 
     if test "$HAVE_64BIT_OS"; then
-    	AC_DEFINE(_WIN64)
+      AC_DEFINE(_WIN64)
     fi
     ;;
 
@@ -2288,17 +2288,17 @@ ia64*-hpux*)
         DLL_SUFFIX=".so"
         DSO_PIC_CFLAGS='-fPIC -DPIC'
         DSO_LDOPTS='-shared'
-	BIN_FLAGS='-Wl,--export-dynamic'
+  BIN_FLAGS='-Wl,--export-dynamic'
     else
-    	DSO_PIC_CFLAGS='-fPIC -DPIC'
-    	DLL_SUFFIX=".so.1.0"
-    	DSO_LDOPTS='-shared'
+      DSO_PIC_CFLAGS='-fPIC -DPIC'
+      DLL_SUFFIX=".so.1.0"
+      DSO_LDOPTS='-shared'
     fi
     # This will fail on a.out systems prior to 1.5.1_ALPHA.
     MKSHLIB_FORCE_ALL='-Wl,--whole-archive'
     MKSHLIB_UNFORCE_ALL='-Wl,--no-whole-archive'
     if test "$LIBRUNPATH"; then
-	DSO_LDOPTS="-Wl,-R$LIBRUNPATH $DSO_LDOPTS"
+  DSO_LDOPTS="-Wl,-R$LIBRUNPATH $DSO_LDOPTS"
     fi
     MKSHLIB='$(CXX) $(CXXFLAGS) $(DSO_PIC_CFLAGS) $(DSO_LDOPTS) -Wl,-soname,lib$(LIBRARY_NAME)$(DLL_SUFFIX) -o $@'
     MKCSHLIB='$(CC) $(CFLAGS) $(DSO_PIC_CFLAGS) $(DSO_LDOPTS) -Wl,-soname,lib$(LIBRARY_NAME)$(DLL_SUFFIX) -o $@'
@@ -2315,7 +2315,7 @@ ia64*-hpux*)
     DSO_PIC_CFLAGS='-fPIC'
     DSO_LDOPTS='-shared -fPIC'
     if test "$LIBRUNPATH"; then
-	DSO_LDOPTS="-R$LIBRUNPATH $DSO_LDOPTS"
+  DSO_LDOPTS="-R$LIBRUNPATH $DSO_LDOPTS"
     fi
     ;;
 
@@ -3018,10 +3018,10 @@ AC_SUBST(HAVE_DTRACE)
 
 case $target in
 *-aix4.3*|*-aix5*)
-	;;
+  ;;
 *)
-	MOZ_CHECK_HEADERS(sys/cdefs.h)
-	;;
+  MOZ_CHECK_HEADERS(sys/cdefs.h)
+  ;;
 esac
 
 MOZ_LINUX_PERF_EVENT
@@ -3030,10 +3030,10 @@ dnl Checks for libraries.
 dnl ========================================================
 case $target in
 *-hpux11.*)
-	;;
+  ;;
 *)
-	AC_CHECK_LIB(c_r, gethostbyname_r)
-	;;
+  AC_CHECK_LIB(c_r, gethostbyname_r)
+  ;;
 esac
 
 dnl We don't want to link with libdl even if it's present on OS X, since
@@ -3063,11 +3063,11 @@ if test ! "$GNU_CXX"; then
 
     case $target in
     *-aix*)
-	AC_CHECK_LIB(C_r, demangle)
-	;;
+  AC_CHECK_LIB(C_r, demangle)
+  ;;
      *)
-	AC_CHECK_LIB(C, demangle)
-	;;
+  AC_CHECK_LIB(C, demangle)
+  ;;
      esac
 fi
 
@@ -3091,20 +3091,20 @@ if test "$no_x" = "yes"; then
     AC_DEFINE(NO_X11)
 else
     AC_DEFINE_UNQUOTED(FUNCPROTO,15)
-	XLIBS="-lX11 $XLIBS"
-	_SAVE_LDFLAGS="$LDFLAGS"
-	LDFLAGS="$XLDFLAGS $LDFLAGS"
-	AC_CHECK_LIB(X11, XDrawLines, [X11_LIBS="-lX11"],
-		[MISSING_X="$MISSING_X -lX11"], $XLIBS)
-	AC_CHECK_LIB(Xext, XextAddDisplay, [XEXT_LIBS="-lXext"],
-		[MISSING_X="$MISSING_X -lXext"], $XLIBS)
+  XLIBS="-lX11 $XLIBS"
+  _SAVE_LDFLAGS="$LDFLAGS"
+  LDFLAGS="$XLDFLAGS $LDFLAGS"
+  AC_CHECK_LIB(X11, XDrawLines, [X11_LIBS="-lX11"],
+    [MISSING_X="$MISSING_X -lX11"], $XLIBS)
+  AC_CHECK_LIB(Xext, XextAddDisplay, [XEXT_LIBS="-lXext"],
+    [MISSING_X="$MISSING_X -lXext"], $XLIBS)
 
-	AC_CHECK_LIB(Xt, XtFree, [ XT_LIBS="-lXt"], [
+  AC_CHECK_LIB(Xt, XtFree, [ XT_LIBS="-lXt"], [
         unset ac_cv_lib_Xt_XtFree
-	    AC_CHECK_LIB(ICE, IceFlush, [XT_LIBS="-lICE $XT_LIBS"],, $XT_LIBS $XLIBS)
-	    AC_CHECK_LIB(SM, SmcCloseConnection, [XT_LIBS="-lSM $XT_LIBS"],, $XT_LIBS $XLIBS)
+      AC_CHECK_LIB(ICE, IceFlush, [XT_LIBS="-lICE $XT_LIBS"],, $XT_LIBS $XLIBS)
+      AC_CHECK_LIB(SM, SmcCloseConnection, [XT_LIBS="-lSM $XT_LIBS"],, $XT_LIBS $XLIBS)
         AC_CHECK_LIB(Xt, XtFree, [ XT_LIBS="-lXt $XT_LIBS"],
-		    [MISSING_X="$MISSING_X -lXt"], $X_PRE_LIBS $XT_LIBS $XLIBS)
+        [MISSING_X="$MISSING_X -lXt"], $X_PRE_LIBS $XT_LIBS $XLIBS)
         ])
 
     # AIX needs the motif library linked before libXt to prevent
@@ -3129,7 +3129,7 @@ else
             [XSS_LIBS="-lXss $XEXT_LIBS $XLIBS"
              AC_DEFINE(HAVE_LIBXSS)],, $XEXT_LIBS $XLIBS))
 
-	LDFLAGS="$_SAVE_LDFLAGS"
+  LDFLAGS="$_SAVE_LDFLAGS"
 fi # $no_x
 
 AC_SUBST(XCFLAGS)
@@ -3180,89 +3180,89 @@ dnl Do the platform specific pthread hackery
 dnl ========================================================
 if test "$USE_PTHREADS"x != x
 then
-	dnl
-	dnl See if -pthread is supported.
-	dnl
-	rm -f conftest*
-	ac_cv_have_dash_pthread=no
-	AC_MSG_CHECKING(whether ${CC-cc} accepts -pthread)
-	echo 'int main() { return 0; }' | cat > conftest.c
-	${CC-cc} -pthread -o conftest conftest.c > conftest.out 2>&1
-	if test $? -eq 0; then
-		if test -z "`egrep -i '(unrecognize|unknown)' conftest.out | grep pthread`" -a -z "`egrep -i '(error|incorrect)' conftest.out`" ; then
-			ac_cv_have_dash_pthread=yes
-	        case "$target_os" in
-	        freebsd*)
+  dnl
+  dnl See if -pthread is supported.
+  dnl
+  rm -f conftest*
+  ac_cv_have_dash_pthread=no
+  AC_MSG_CHECKING(whether ${CC-cc} accepts -pthread)
+  echo 'int main() { return 0; }' | cat > conftest.c
+  ${CC-cc} -pthread -o conftest conftest.c > conftest.out 2>&1
+  if test $? -eq 0; then
+    if test -z "`egrep -i '(unrecognize|unknown)' conftest.out | grep pthread`" -a -z "`egrep -i '(error|incorrect)' conftest.out`" ; then
+      ac_cv_have_dash_pthread=yes
+          case "$target_os" in
+          freebsd*)
 # Freebsd doesn't use -pthread for compiles, it uses them for linking
                 ;;
-	        *)
-			    CFLAGS="$CFLAGS -pthread"
-			    CXXFLAGS="$CXXFLAGS -pthread"
+          *)
+          CFLAGS="$CFLAGS -pthread"
+          CXXFLAGS="$CXXFLAGS -pthread"
                 ;;
-	        esac
-		fi
-	fi
-	rm -f conftest*
+          esac
+    fi
+  fi
+  rm -f conftest*
     AC_MSG_RESULT($ac_cv_have_dash_pthread)
 
-	dnl
-	dnl See if -pthreads is supported.
-	dnl
+  dnl
+  dnl See if -pthreads is supported.
+  dnl
     ac_cv_have_dash_pthreads=no
     if test "$ac_cv_have_dash_pthread" = "no"; then
-	    AC_MSG_CHECKING(whether ${CC-cc} accepts -pthreads)
-    	echo 'int main() { return 0; }' | cat > conftest.c
-	    ${CC-cc} -pthreads -o conftest conftest.c > conftest.out 2>&1
-    	if test $? -eq 0; then
-	    	if test -z "`egrep -i '(unrecognize|unknown)' conftest.out | grep pthreads`" -a -z "`egrep -i '(error|incorrect)' conftest.out`" ; then
-			    ac_cv_have_dash_pthreads=yes
-			    CFLAGS="$CFLAGS -pthreads"
-			    CXXFLAGS="$CXXFLAGS -pthreads"
-		    fi
-	    fi
-	    rm -f conftest*
-    	AC_MSG_RESULT($ac_cv_have_dash_pthreads)
+      AC_MSG_CHECKING(whether ${CC-cc} accepts -pthreads)
+      echo 'int main() { return 0; }' | cat > conftest.c
+      ${CC-cc} -pthreads -o conftest conftest.c > conftest.out 2>&1
+      if test $? -eq 0; then
+        if test -z "`egrep -i '(unrecognize|unknown)' conftest.out | grep pthreads`" -a -z "`egrep -i '(error|incorrect)' conftest.out`" ; then
+          ac_cv_have_dash_pthreads=yes
+          CFLAGS="$CFLAGS -pthreads"
+          CXXFLAGS="$CXXFLAGS -pthreads"
+        fi
+      fi
+      rm -f conftest*
+      AC_MSG_RESULT($ac_cv_have_dash_pthreads)
     fi
 
-	case "$target" in
-	    *-*-freebsd*)
-			AC_DEFINE(_REENTRANT)
-			AC_DEFINE(_THREAD_SAFE)
-			dnl -pthread links in -lpthread, so don't specify it explicitly.
-			if test "$ac_cv_have_dash_pthread" = "yes"; then
-				_PTHREAD_LDFLAGS="-pthread"
-			fi
-			;;
+  case "$target" in
+      *-*-freebsd*)
+      AC_DEFINE(_REENTRANT)
+      AC_DEFINE(_THREAD_SAFE)
+      dnl -pthread links in -lpthread, so don't specify it explicitly.
+      if test "$ac_cv_have_dash_pthread" = "yes"; then
+        _PTHREAD_LDFLAGS="-pthread"
+      fi
+      ;;
 
-	    *-*-openbsd*|*-*-bsdi*)
-			AC_DEFINE(_REENTRANT)
-			AC_DEFINE(_THREAD_SAFE)
-			dnl -pthread links in -lc_r, so don't specify it explicitly.
-			if test "$ac_cv_have_dash_pthread" = "yes"; then
+      *-*-openbsd*|*-*-bsdi*)
+      AC_DEFINE(_REENTRANT)
+      AC_DEFINE(_THREAD_SAFE)
+      dnl -pthread links in -lc_r, so don't specify it explicitly.
+      if test "$ac_cv_have_dash_pthread" = "yes"; then
                 _PTHREAD_LDFLAGS="-pthread"
-			fi
-			;;
+      fi
+      ;;
 
-	    *-*-linux*|*-*-kfreebsd*-gnu|*-*-gnu*)
-			AC_DEFINE(_REENTRANT)
-			;;
+      *-*-linux*|*-*-kfreebsd*-gnu|*-*-gnu*)
+      AC_DEFINE(_REENTRANT)
+      ;;
 
-	    *-aix4.3*|*-aix5*)
-			AC_DEFINE(_REENTRANT)
-			;;
+      *-aix4.3*|*-aix5*)
+      AC_DEFINE(_REENTRANT)
+      ;;
 
-	    *-hpux11.*)
-			AC_DEFINE(_REENTRANT)
-			;;
+      *-hpux11.*)
+      AC_DEFINE(_REENTRANT)
+      ;;
 
-	    *-*-solaris*)
-			AC_DEFINE(_REENTRANT)
-			if test "$SOLARIS_SUNPRO_CC"; then
-				CFLAGS="$CFLAGS -mt"
-				CXXFLAGS="$CXXFLAGS -mt"
-			fi
-			;;
-	esac
+      *-*-solaris*)
+      AC_DEFINE(_REENTRANT)
+      if test "$SOLARIS_SUNPRO_CC"; then
+        CFLAGS="$CFLAGS -mt"
+        CXXFLAGS="$CXXFLAGS -mt"
+      fi
+      ;;
+  esac
     LDFLAGS="${_PTHREAD_LDFLAGS} ${LDFLAGS}"
 fi
 
@@ -3776,11 +3776,11 @@ dnl features go here.
 
 dnl check for LC_MESSAGES
 AC_CACHE_CHECK(for LC_MESSAGES,
-		ac_cv_i18n_lc_messages,
-		[AC_TRY_COMPILE([#include <locale.h>],
-				[int category = LC_MESSAGES;],
-				ac_cv_i18n_lc_messages=yes,
-				ac_cv_i18n_lc_messages=no)])
+    ac_cv_i18n_lc_messages,
+    [AC_TRY_COMPILE([#include <locale.h>],
+        [int category = LC_MESSAGES;],
+        ac_cv_i18n_lc_messages=yes,
+        ac_cv_i18n_lc_messages=no)])
 if test "$ac_cv_i18n_lc_messages" = yes; then
    AC_DEFINE(HAVE_I18N_LC_MESSAGES)
 fi
@@ -4082,7 +4082,7 @@ if test -z "$BZ2_DIR" -o "$BZ2_DIR" = no; then
     MOZ_NATIVE_BZ2=
 else
     AC_CHECK_LIB(bz2, BZ2_bzread, [MOZ_NATIVE_BZ2=1 MOZ_BZ2_LIBS="-lbz2"],
-	[MOZ_NATIVE_BZ2= MOZ_BZ2_CFLAGS= MOZ_BZ2_LIBS=])
+  [MOZ_NATIVE_BZ2= MOZ_BZ2_CFLAGS= MOZ_BZ2_LIBS=])
 fi
 CFLAGS=$_SAVE_CFLAGS
 LDFLAGS=$_SAVE_LDFLAGS
@@ -4466,8 +4466,8 @@ MOZ_ARG_HEADER(Toolkit Options)
     dnl ========================================================
     dnl = Select the default toolkit
     dnl ========================================================
-	MOZ_ARG_ENABLE_STRING(default-toolkit,
-	[  --enable-default-toolkit=TK
+  MOZ_ARG_ENABLE_STRING(default-toolkit,
+  [  --enable-default-toolkit=TK
                           Select default toolkit
                           Platform specific defaults:
                             Mac OS X - cairo-cocoa
@@ -5915,7 +5915,7 @@ if test -n "$MOZ_ANGLE_RENDERER" -a -z "$CROSS_COMPILE"; then
 
   if test -n "$MOZ_DIRECTX_SDK_PATH" &&
      test -f "$MOZ_DIRECTX_SDK_PATH"/include/d3dx9.h &&
-	 test -f "$MOZ_DIRECTX_SDK_PATH"/lib/$MOZ_DIRECTX_SDK_CPU_SUFFIX/dxguid.lib ; then
+   test -f "$MOZ_DIRECTX_SDK_PATH"/lib/$MOZ_DIRECTX_SDK_CPU_SUFFIX/dxguid.lib ; then
     AC_MSG_RESULT([Found DirectX SDK via registry, using $MOZ_DIRECTX_SDK_PATH])
   else
     AC_MSG_ERROR([Couldn't find the DirectX SDK, needed for WebGL. Either install it (June 2010 version or newer), or reconfigure with --disable-webgl.])
@@ -5925,7 +5925,7 @@ if test -n "$MOZ_ANGLE_RENDERER" -a -z "$CROSS_COMPILE"; then
   MOZ_D3DX9_VERSION=`dumpbin //headers "$MOZ_DIRECTX_SDK_PATH"/lib/$MOZ_DIRECTX_SDK_CPU_SUFFIX/d3dx9.lib | egrep d3dx9_[[0-9]][[0-9]]\.dll | head -n1 | sed 's/.*\([[0-9]][[0-9]]\).*/\\1/g'`
 
   if test -z "$MOZ_D3DX9_VERSION" ; then
-  	AC_MSG_ERROR([Couldn't determine the D3DX9 version, needed for WebGL. Either reinstall the DirectX SDK (June 2010 version or newer), or reconfigure with --disable-webgl.])
+    AC_MSG_ERROR([Couldn't determine the D3DX9 version, needed for WebGL. Either reinstall the DirectX SDK (June 2010 version or newer), or reconfigure with --disable-webgl.])
   fi
 
   MOZ_D3DCOMPILER_CAB=`find "$MOZ_DIRECTX_SDK_PATH"/Redist -name *D3DCompiler_${MOZ_D3DX9_VERSION}_${MOZ_DIRECTX_SDK_CPU_SUFFIX}.cab | head -n1`
@@ -6907,7 +6907,7 @@ dnl ========================================================
 dnl = Enable code optimization. ON by default.
 dnl ========================================================
 if test -z "$MOZ_OPTIMIZE_FLAGS"; then
-	MOZ_OPTIMIZE_FLAGS="-O"
+  MOZ_OPTIMIZE_FLAGS="-O"
 fi
 
 MOZ_ARG_ENABLE_STRING(optimize,
@@ -8719,21 +8719,21 @@ AC_SUBST(MAKENSISU)
 
 dnl Echo the CFLAGS to remove extra whitespace.
 CFLAGS=`echo \
-	$_WARNINGS_CFLAGS \
-	$CFLAGS`
+  $_WARNINGS_CFLAGS \
+  $CFLAGS`
 
 CXXFLAGS=`echo \
-	$_WARNINGS_CXXFLAGS \
-	$CXXFLAGS`
+  $_WARNINGS_CXXFLAGS \
+  $CXXFLAGS`
 
 COMPILE_CFLAGS=`echo \
     $_DEFINES_CFLAGS \
-	$_DEPEND_CFLAGS \
+  $_DEPEND_CFLAGS \
     $COMPILE_CFLAGS`
 
 COMPILE_CXXFLAGS=`echo \
     $_DEFINES_CXXFLAGS \
-	$_DEPEND_CFLAGS \
+  $_DEPEND_CFLAGS \
     $COMPILE_CXXFLAGS`
 
 AC_SUBST(SYSTEM_LIBXUL)
